# Generated by Django 3.1 on 2021-06-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('general', 'General enquiry'), ('bug', 'Bug report'), ('suggestion', 'Suggestion')], max_length=40)),
                ('message', models.CharField(max_length=200)),
                ('sender', models.EmailField(max_length=254)),
            ],
        ),
    ]
