# Generated by Django 3.1 on 2021-06-25 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_contactmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactModel',
            new_name='Contact',
        ),
    ]
