# Generated by Django 3.1 on 2021-06-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210626_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sender',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
