# Generated by Django 3.1 on 2021-09-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210626_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
